<?php

use Illuminate\Database\Seeder;

class AreasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert('
            INSERT INTO `areas` (`state_id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES
            (1, "Airport Street", NOW(), NOW(), NOW()),
            (1, "Al Bateen", NOW(), NOW(), NOW()),
            (1, "Al Bateen Airport", NOW(), NOW(), NOW()),
            (1, "Al Dhafrah", NOW(), NOW(), NOW()),
            (1, "Al Hosn", NOW(), NOW(), NOW()),
            (1, "Al Karamah", NOW(), NOW(), NOW()),
            (1, "Al Khalidiyah", NOW(), NOW(), NOW()),
            (1, "Al Khubeirah", NOW(), NOW(), NOW()),
            (1, "Al Mafraq", NOW(), NOW(), NOW()),
            (1, "Al Manhal", NOW(), NOW(), NOW()),
            (1, "Maqta Bridge", NOW(), NOW(), NOW()),
            (1, "Al Markaziya", NOW(), NOW(), NOW()),
            (1, "Al Mushrif", NOW(), NOW(), NOW()),
            (1, "Al Raha Beach", NOW(), NOW(), NOW()),
            (1, "Al Reef Downtown", NOW(), NOW(), NOW()),
            (1, "Al Reef", NOW(), NOW(), NOW()),
            (1, "Al Reem Island", NOW(), NOW(), NOW()),
            (1, "Al Riyadiya", NOW(), NOW(), NOW()),
            (1, "Al Rowdah", NOW(), NOW(), NOW()),
            (1, "Al Tabbiyah", NOW(), NOW(), NOW()),
            (1, "Building Material City", NOW(), NOW(), NOW()),
            (1, "Central Market", NOW(), NOW(), NOW()),
            (1, "Coconut Island", NOW(), NOW(), NOW()),
            (1, "Danet Gateway", NOW(), NOW(), NOW()),
            (1, "Hadbat al Zaafarana", NOW(), NOW(), NOW()),
            (1, "Hoderiyyat", NOW(), NOW(), NOW()),
            (1, "Hydra Golf Walk", NOW(), NOW(), NOW()),
            (1, "Hydra Village", NOW(), NOW(), NOW()),
            (1, "Industrial City Of Abu Dhabi", NOW(), NOW(), NOW()),
            (1, "Khalifa City A", NOW(), NOW(), NOW()),
            (1, "Khalifa Street", NOW(), NOW(), NOW()),
            (1, "Khor Al Maqta", NOW(), NOW(), NOW()),
            (1, "Lulu Island", NOW(), NOW(), NOW()),
            (1, "Madinat Zayed Abu Dhabi City", NOW(), NOW(), NOW()),
            (1, "Mangrove One", NOW(), NOW(), NOW()),
            (1, "Marina Village", NOW(), NOW(), NOW()),
            (1, "Mina Zayed Port", NOW(), NOW(), NOW()),
            (1, "Mohammed Bin Zayed City", NOW(), NOW(), NOW()),
            (1, "Mushayrib Island", NOW(), NOW(), NOW()),
            (1, "Mussafah", NOW(), NOW(), NOW()),
            (1, "Nurai Island", NOW(), NOW(), NOW()),
            (1, "Officers City", NOW(), NOW(), NOW()),
            (1, "Qasr Al Sarab", NOW(), NOW(), NOW()),
            (1, "Qasr Al Bahar", NOW(), NOW(), NOW()),
            (1, "Ras Al Akhdar", NOW(), NOW(), NOW()),
            (1, "Saadiyat Island", NOW(), NOW(), NOW()),
            (1, "Salam Street", NOW(), NOW(), NOW()),
            (1, "Saraya", NOW(), NOW(), NOW()),
            (1, "Garden Tower", NOW(), NOW(), NOW()),
            (1, "Other", NOW(), NOW(), NOW()),
            (1, "Al Raha Gardens", NOW(), NOW(), NOW()),
            (1, "Old Mazda Road", NOW(), NOW(), NOW()),
            (1, "Khalifa Energy Complex", NOW(), NOW(), NOW()),
            (1, "Hamdan Street", NOW(), NOW(), NOW()),
            (1, "Abu-Dhabi Mall", NOW(), NOW(), NOW()),
            (1, "Al-Najda Street", NOW(), NOW(), NOW()),
            (1, "Ziany Area", NOW(), NOW(), NOW()),
            (1, "Hamdan Post Office", NOW(), NOW(), NOW()),
            (1, "Electra Street", NOW(), NOW(), NOW()),
            (1, "Khalifa Park", NOW(), NOW(), NOW()),
            (1, "Officer Club", NOW(), NOW(), NOW()),
            (1, "Zayed Sports City", NOW(), NOW(), NOW()),
            (1, "Abu Dhabi Muncipality", NOW(), NOW(), NOW()),
            (1, "Abu-Dhabi Indian School", NOW(), NOW(), NOW()),
            (1, "Al-Naser Street", NOW(), NOW(), NOW()),
            (1, "Corniche", NOW(), NOW(), NOW()),
            (1, "Marina Mall", NOW(), NOW(), NOW()),
            (1, "Istiklal Street", NOW(), NOW(), NOW()),
            (1, "Baynoonah Street", NOW(), NOW(), NOW()),
            (1, "Khalidiya Mall", NOW(), NOW(), NOW()),
            (1, "Khalidiya Village", NOW(), NOW(), NOW()),
            (1, "Emirates Palace Hotel", NOW(), NOW(), NOW()),
            (1, "Bateen Towers", NOW(), NOW(), NOW()),
            (1, "Carrefour Airport Road", NOW(), NOW(), NOW()),
            (1, "Al Zaab", NOW(), NOW(), NOW()),
            (1, "SKMC", NOW(), NOW(), NOW()),
            (1, "Al-Khaleej Al-Arabi St", NOW(), NOW(), NOW()),
            (1, "Int\'l school of Choueifat ", NOW(), NOW(), NOW()),
            (1, "Al-Saada Street", NOW(), NOW(), NOW()),
            (1, "Embassy Area", NOW(), NOW(), NOW()),
            (1, "Al-Falah street", NOW(), NOW(), NOW()),
            (1, "Abu Dhabi Exhibition Centre (ADNEC)", NOW(), NOW(), NOW()),
            (1, "Al-Noor Hospital", NOW(), NOW(), NOW()),
            (1, "Abu-Dhabi Police Academy", NOW(), NOW(), NOW()),
            (1, "Police College", NOW(), NOW(), NOW()),
            (1, "Abu-Dhabi Traffic", NOW(), NOW(), NOW()),
            (1, "Defence Road", NOW(), NOW(), NOW()),
            (1, "Al Nahyan", NOW(), NOW(), NOW()),
            (1, "Delma Street", NOW(), NOW(), NOW()),
            (1, "Abu-Dhabi Bus Station", NOW(), NOW(), NOW()),
            (1, "Al Wahda", NOW(), NOW(), NOW()),
            (1, "Abu Dhabi Media Co", NOW(), NOW(), NOW()),
            (1, "Hazza Bin Zayed Street", NOW(), NOW(), NOW()),
            (1, "Al Dhafra Air Base Area", NOW(), NOW(), NOW()),
            (1, "Mussafah Industrial Area", NOW(), NOW(), NOW()),
            (1, "Mussafah Shabia", NOW(), NOW(), NOW()),
            (1, "Mussafah Police Station Area", NOW(), NOW(), NOW()),
            (1, "Emirates Driving Co.", NOW(), NOW(), NOW()),
            (1, "Abu-Dhabi Golf club & Resort", NOW(), NOW(), NOW()),
            (1, "Khalifha City B", NOW(), NOW(), NOW()),
            (1, "Between The Bridges", NOW(), NOW(), NOW()),
            (1, "Umm Al Nar", NOW(), NOW(), NOW()),
            (1, "SAS Al Nakheel Village", NOW(), NOW(), NOW()),
            (1, "Petrolium Institute", NOW(), NOW(), NOW()),
            (1, "Abu-Dhabi Motor co", NOW(), NOW(), NOW()),
            (1, "Baniyas (East)", NOW(), NOW(), NOW()),
            (1, "Baniyas (West)", NOW(), NOW(), NOW()),
            (1, "Rahba", NOW(), NOW(), NOW()),
            (1, "Yas Island", NOW(), NOW(), NOW()),
            (1, "Ferrari World", NOW(), NOW(), NOW()),
            (1, "Al-Dar Lang ", NOW(), NOW(), NOW()),
            (1, "Old Shahamma", NOW(), NOW(), NOW()),
            (1, "New Shahamma", NOW(), NOW(), NOW()),
            (1, "Al-Shamkha", NOW(), NOW(), NOW()),
            (1, "Shwamakh", NOW(), NOW(), NOW()),
            (1, "Samha Area", NOW(), NOW(), NOW()),
            (1, "Al-Bahia -A", NOW(), NOW(), NOW()),
            (1, "Al Bahya (New Bahya)", NOW(), NOW(), NOW()),
            (1, "Al-Falah City", NOW(), NOW(), NOW()),
            (1, "Abu-Dhabi Int\'l Airport", NOW(), NOW(), NOW()),
            (1, "Masdar City", NOW(), NOW(), NOW()),
            (1, "Al Maryah Island", NOW(), NOW(), NOW()),
            (1, "Navy Gate", NOW(), NOW(), NOW()),
            (1, "Lulu Street", NOW(), NOW(), NOW()),
            (1, "Sheikh Khalifa Medical City", NOW(), NOW(), NOW()),
            (1, "Diplomatic Area", NOW(), NOW(), NOW()),
            (1, "W 14-02", NOW(), NOW(), NOW()),
            (1, "W 15-02", NOW(), NOW(), NOW()),
            (1, "Hadharem", NOW(), NOW(), NOW()),
            (1, "ADCO Compound", NOW(), NOW(), NOW()),
            (1, "Qasr al Shati Area", NOW(), NOW(), NOW()),
            (1, "Daratul Mia", NOW(), NOW(), NOW()),
            (1, "Fairmont Residences", NOW(), NOW(), NOW()),
            (1, "Orynx Gardens", NOW(), NOW(), NOW()),
            (1, "Saadiyat Marina District", NOW(), NOW(), NOW()),
            (1, "Baniyas City", NOW(), NOW(), NOW()),
            (1, "Bawabat Al Sharq", NOW(), NOW(), NOW()),
            (1, "Al Jaber Mafraq Camp", NOW(), NOW(), NOW()),
            (1, "Mafraq Workers City", NOW(), NOW(), NOW()),
            (1, "Al Wathba", NOW(), NOW(), NOW()),
            (1, "Al Wathba South New", NOW(), NOW(), NOW()),
            (1, "Watani Project", NOW(), NOW(), NOW()),
            (1, "Rawdat Al Reef", NOW(), NOW(), NOW()),
            (1, "Arabian Village", NOW(), NOW(), NOW()),
            (1, "Contemporary Village", NOW(), NOW(), NOW()),
            (1, "Desert Village", NOW(), NOW(), NOW()),
            (1, "Mediterranean Village", NOW(), NOW(), NOW()),
            (1, "Al Shalila", NOW(), NOW(), NOW()),
            (1, "Al Bahya", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 1", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 10", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 11", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 12", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 13", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 14", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 15", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 16", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 17", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 18", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 19", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 2", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 20", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 21", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 22", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 23", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 24", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 25", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 26", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 27", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 28", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 29", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 3", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 30", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 31", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 4", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 5", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 6", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 7", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 8", NOW(), NOW(), NOW()),
            (1, "Shakhbout Block 9", NOW(), NOW(), NOW()),
            (2, "Ain Ajman", NOW(), NOW(), NOW()),
            (2, "Ajman Marina", NOW(), NOW(), NOW()),
            (2, "Ajman Meadows", NOW(), NOW(), NOW()),
            (2, "Ajman Uptown", NOW(), NOW(), NOW()),
            (2, "Ajman Villas", NOW(), NOW(), NOW()),
            (2, "Al Ameera Village", NOW(), NOW(), NOW()),
            (2, "Al Bustan", NOW(), NOW(), NOW()),
            (2, "Al Butain", NOW(), NOW(), NOW()),
            (2, "Al Hamidiya", NOW(), NOW(), NOW()),
            (2, "Al Helio City", NOW(), NOW(), NOW()),
            (2, "Al Humaid City", NOW(), NOW(), NOW()),
            (2, "Al Ittihad Village", NOW(), NOW(), NOW()),
            (2, "Al Jerf Gardens", NOW(), NOW(), NOW()),
            (2, "Al Karama Ajman", NOW(), NOW(), NOW()),
            (2, "Al Karama Area", NOW(), NOW(), NOW()),
            (2, "Al Man1 Tower", NOW(), NOW(), NOW()),
            (2, "Al Nakhil", NOW(), NOW(), NOW()),
            (2, "Al Noor Tower Ajman", NOW(), NOW(), NOW()),
            (2, "Al Owan", NOW(), NOW(), NOW()),
            (2, "Al Rashidia", NOW(), NOW(), NOW()),
            (2, "Al Rumaila", NOW(), NOW(), NOW()),
            (2, "Al Zorah", NOW(), NOW(), NOW()),
            (2, "Aqua City", NOW(), NOW(), NOW()),
            (2, "Awali City", NOW(), NOW(), NOW()),
            (2, "Chapal Flora", NOW(), NOW(), NOW()),
            (2, "Emirates City", NOW(), NOW(), NOW()),
            (2, "Escape Ajman", NOW(), NOW(), NOW()),
            (2, "Eye Of Ajman", NOW(), NOW(), NOW()),
            (2, "Freej Balushi", NOW(), NOW(), NOW()),
            (2, "Green City", NOW(), NOW(), NOW()),
            (2, "Jurf", NOW(), NOW(), NOW()),
            (2, "Marmooka City", NOW(), NOW(), NOW()),
            (2, "Naemiyah", NOW(), NOW(), NOW()),
            (2, "New Industrial City", NOW(), NOW(), NOW()),
            (2, "Onyx City", NOW(), NOW(), NOW()),
            (2, "Park View City", NOW(), NOW(), NOW()),
            (2, "Rumaila Area", NOW(), NOW(), NOW()),
            (2, "Old Industrial Area", NOW(), NOW(), NOW()),
            (2, "Liwara", NOW(), NOW(), NOW()),
            (2, "Sowan", NOW(), NOW(), NOW()),
            (2, "Ajman Freezone", NOW(), NOW(), NOW()),
            (2, "Mishrif City", NOW(), NOW(), NOW()),
            (2, "Sanaya Industrial Area", NOW(), NOW(), NOW()),
            (2, "Rumaila", NOW(), NOW(), NOW()),
            (2, "Falcon Tower", NOW(), NOW(), NOW()),
            (2, "Hamriya Freezone", NOW(), NOW(), NOW()),
            (2, "Al-Zahra", NOW(), NOW(), NOW()),
            (2, "Muwaihath", NOW(), NOW(), NOW()),
            (2, "GMC", NOW(), NOW(), NOW()),
            (2, "New Industrial Area", NOW(), NOW(), NOW()),
            (2, "Ajman City Centre", NOW(), NOW(), NOW()),
            (2, "Hamriya Town", NOW(), NOW(), NOW()),
            (2, "Mishrif Villas", NOW(), NOW(), NOW()),
            (2, "Hamdiya -Jarf", NOW(), NOW(), NOW()),
            (2, "Ajman University", NOW(), NOW(), NOW()),
            (2, "Fewa Ajman", NOW(), NOW(), NOW()),
            (2, "Ajman Police Headquarters", NOW(), NOW(), NOW()),
            (2, "Aamra", NOW(), NOW(), NOW()),
            (2, "Yasmeen", NOW(), NOW(), NOW()),
            (2, "Al Zahya", NOW(), NOW(), NOW()),
            (2, "Al Muntazi 1", NOW(), NOW(), NOW()),
            (2, "Al Muntazi 2", NOW(), NOW(), NOW()),
            (2, "Al Tallah 1", NOW(), NOW(), NOW()),
            (2, "Al Tallah 2", NOW(), NOW(), NOW()),
            (2, "Safia", NOW(), NOW(), NOW()),
            (2, "Al Bahia", NOW(), NOW(), NOW()),
            (2, "Al Raqaib 1", NOW(), NOW(), NOW()),
            (2, "Al Raqaib 2", NOW(), NOW(), NOW()),
            (2, "Ajman Industrial 2", NOW(), NOW(), NOW()),
            (3, "Zakhir", NOW(), NOW(), NOW()),
            (3, "Al Foah Area", NOW(), NOW(), NOW()),
            (3, "Al Jimi", NOW(), NOW(), NOW()),
            (3, "Al Maqam", NOW(), NOW(), NOW()),
            (3, "Al Sarooj", NOW(), NOW(), NOW()),
            (3, "New Manasir", NOW(), NOW(), NOW()),
            (3, "Al Mutarad", NOW(), NOW(), NOW()),
            (3, "Al-Mutarad", NOW(), NOW(), NOW()),
            (3, "Al-Muwaiji", NOW(), NOW(), NOW()),
            (3, "Al Bateen", NOW(), NOW(), NOW()),
            (3, "Gafat Al Nayyar", NOW(), NOW(), NOW()),
            (3, "Al Grayyeh", NOW(), NOW(), NOW()),
            (3, "Central District ( Town Center )", NOW(), NOW(), NOW()),
            (3, "Al Ain Zoo and Aquarium", NOW(), NOW(), NOW()),
            (3, "Jebel hafeet", NOW(), NOW(), NOW()),
            (3, "Al Towayya", NOW(), NOW(), NOW()),
            (3, "Al Muwaiji", NOW(), NOW(), NOW()),
            (3, "Hili", NOW(), NOW(), NOW()),
            (3, "Al Masoudi", NOW(), NOW(), NOW()),
            (3, "Al Qattara", NOW(), NOW(), NOW()),
            (3, "Al Ain Fun City", NOW(), NOW(), NOW()),
            (3, "Falaj Hazzaa", NOW(), NOW(), NOW()),
            (3, "New Al Sanaiya", NOW(), NOW(), NOW()),
            (3, "Al Yahar", NOW(), NOW(), NOW()),
            (3, "Salamat", NOW(), NOW(), NOW()),
            (3, "Al Saad", NOW(), NOW(), NOW()),
            (3, "Al Shwaib", NOW(), NOW(), NOW()),
            (3, "Al Dhaher", NOW(), NOW(), NOW()),
            (3, "Abu Samra", NOW(), NOW(), NOW()),
            (3, "Sweihan", NOW(), NOW(), NOW()),
            (3, "Shiab Al Ashkhar", NOW(), NOW(), NOW()),
            (3, "Green Mubazzarah", NOW(), NOW(), NOW()),
            (3, "Airport District", NOW(), NOW(), NOW()),
            (3, "Um Ghafa", NOW(), NOW(), NOW()),
            (3, "Neima", NOW(), NOW(), NOW()),
            (3, "Al Ain Industrial Area", NOW(), NOW(), NOW()),
            (3, "Wadi Al Ain 3 - Al Khrair", NOW(), NOW(), NOW()),
            (3, "Wadi Al Ain 2 - Al Khrair", NOW(), NOW(), NOW()),
            (3, "Companies Camp Mezyad", NOW(), NOW(), NOW()),
            (3, "Al Dhaher 5", NOW(), NOW(), NOW()),
            (3, "Um Ghaffa Farms", NOW(), NOW(), NOW()),
            (3, "Al Agaabiya", NOW(), NOW(), NOW()),
            (3, "Ramlat Zakher", NOW(), NOW(), NOW()),
            (3, "Al Suwaifi", NOW(), NOW(), NOW()),
            (3, "Hai Zayed Mosque", NOW(), NOW(), NOW()),
            (3, "Al Shuaibah", NOW(), NOW(), NOW()),
            (3, "Al Khalidiya", NOW(), NOW(), NOW()),
            (3, "Ghrebah", NOW(), NOW(), NOW()),
            (3, "Shaabiyat Al Maqam", NOW(), NOW(), NOW()),
            (3, "UAE University New Campus", NOW(), NOW(), NOW()),
            (3, "Asharej", NOW(), NOW(), NOW()),
            (3, "Hili Sanaya", NOW(), NOW(), NOW()),
            (3, "Msaibeekh", NOW(), NOW(), NOW()),
            (3, "Al Khaleef", NOW(), NOW(), NOW()),
            (3, "Al Khabisi", NOW(), NOW(), NOW()),
            (3, "Al Rifa\'ah", NOW(), NOW(), NOW()),
            (3, "Hai Jafeer Al Jadeed", NOW(), NOW(), NOW()),
            (3, "Magar Al Dhabi", NOW(), NOW(), NOW()),
            (3, "Hazza Bin Zayed Stadium", NOW(), NOW(), NOW()),
            (3, "Al Marakhaniya", NOW(), NOW(), NOW()),
            (3, "Al Dahmaa", NOW(), NOW(), NOW()),
            (4, "Abu Hail",  NOW(), NOW(), NULL),
            (4, "Acacia Avenues",  NOW(), NOW(), NULL),
            (4, "Al Bada\'a",  NOW(), NOW(), NULL),
            (4, "Al Baraha",  NOW(), NOW(), NULL),
            (4, "Al Barsha",  NOW(), NOW(), NULL),
            (4, "Al Buteen",  NOW(), NOW(), NULL),
            (4, "Al Furjan",  NOW(), NOW(), NULL),
            (4, "Al Garhoud",  NOW(), NOW(), NULL),
            (4, "Al Hamriya",  NOW(), NOW(), NULL),
            (4, "Al Hudaiba",  NOW(), NOW(), NULL),
            (4, "Al Jadaf",  NOW(), NOW(), NULL),
            (4, "Al Jafiliya",  NOW(), NOW(), NULL),
            (4, "Al Kaheel",  NOW(), NOW(), NULL),
            (4, "Al Karama",  NOW(), NOW(), NULL),
            (4, "Al Khabaisi",  NOW(), NOW(), NULL),
            (4, "Al Khawaneej",  NOW(), NOW(), NULL),
            (4, "Al Kifaf",  NOW(), NOW(), NULL),
            (4, "Al Manara",  NOW(), NOW(), NULL),
            (4, "Meydan Heights",  NOW(), NOW(), NULL),
            (4, "Al Mizhar",  NOW(), NOW(), NULL),
            (4, "Al Muraqqabat",  NOW(), NOW(), NULL),
            (4, "Al Murar",  NOW(), NOW(), NULL),
            (4, "Al Muteena",  NOW(), NOW(), NULL),
            (4, "Al Nahda",  NOW(), NOW(), NULL),
            (4, "Al Nasr",  NOW(), NOW(), NULL),
            (4, "Al Quoz",  NOW(), NOW(), NULL),
            (4, "Al Qusais",  NOW(), NOW(), NULL),
            (4, "Al Raffa",  NOW(), NOW(), NULL),
            (4, "Al Rashidiya",  NOW(), NOW(), NULL),
            (4, "Al Rigga",  NOW(), NOW(), NULL),
            (4, "Al Safa",  NOW(), NOW(), NULL),
            (4, "Al Satwa",  NOW(), NOW(), NULL),
            (4, "Al Souq Al Kabeer",  NOW(), NOW(), NULL),
            (4, "Al Sufouh",  NOW(), NOW(), NULL),
            (4, "Al Tawar",  NOW(), NOW(), NULL),
            (4, "Al Warqaa",  NOW(), NOW(), NULL),
            (4, "Bu Kadra",  NOW(), NOW(), NULL),
            (4, "Bur Dubai",  NOW(), NOW(), NULL),
            (4, "Business Bay",  NOW(), NOW(), NULL),
            (4, "City of Arabia",  NOW(), NOW(), NULL),
            (4, "Corniche Deira",  NOW(), NOW(), NULL),
            (4, "Culture Village",  NOW(), NOW(), NULL),
            (4, "Deira Dubai",  NOW(), NOW(), NULL),
            (4, "Discovery Gardens",  NOW(), NOW(), NULL),
            (4, "Downtown Dubai",  NOW(), NOW(), NULL),
            (4, "Downtown Jebel Ali",  NOW(), NOW(), NULL),
            (4, "Dubai BioTechnology And Research Park",  NOW(), NOW(), NULL),
            (4, "Dubai Festival City",  NOW(), NOW(), NULL),
            (4, "Dubai industrial Park",  NOW(), NOW(), NULL),
            (4, "Dubai International Academic City",  NOW(), NOW(), NULL),
            (4, "Dubai International Financial Center",  NOW(), NOW(), NULL),
            (4, "Dubai Investment Park 1",  NOW(), NOW(), NULL),
            (4, "Dubai Investment Park 2",  NOW(), NOW(), NULL),
            (4, "Dubailand Residence Complex",  NOW(), NOW(), NULL),
            (4, "Dubai Maritime City",  NOW(), NOW(), NULL),
            (4, "Dubai Pearl",  NOW(), NOW(), NULL),
            (4, "Dubai Silicon Oasis",  NOW(), NOW(), NULL),
            (4, "Sports City",  NOW(), NOW(), NULL),
            (4, "Dubai Waterfront",  NOW(), NOW(), NULL),
            (4, "Dubai World Central",  NOW(), NOW(), NULL),
            (4, "Emirates Hills",  NOW(), NOW(), NULL),
            (4, "Gold Souk",  NOW(), NOW(), NULL),
            (4, "Hor Al Anz",  NOW(), NOW(), NULL),
            (4, "International City",  NOW(), NOW(), NULL),
            (4, "International City Phase 3",  NOW(), NOW(), NULL),
            (4, "International Media Production Zone",  NOW(), NOW(), NULL),
            (4, "Jebel Ali Industrial Areas",  NOW(), NOW(), NULL),
            (4, "Jebel Ali Village",  NOW(), NOW(), NULL),
            (4, "Jumeirah",  NOW(), NOW(), NULL),
            (4, "Jumeirah Beach Residence",  NOW(), NOW(), NULL),
            (4, "Jumeirah Golf Estates",  NOW(), NOW(), NULL),
            (4, "Jumeirah Islands",  NOW(), NOW(), NULL),
            (4, "Jumeirah Lakes Towers",  NOW(), NOW(), NULL),
            (4, "Jumeirah Park",  NOW(), NOW(), NULL),
            (4, "Jumeirah Village South",  NOW(), NOW(), NULL),
            (4, "Jumeirah Village Triangle",  NOW(), NOW(), NULL),
            (4, "Madina Badr",  NOW(), NOW(), NULL),
            (4, "Al Mankhool",  NOW(), NOW(), NULL),
            (4, "Dubai Marina",  NOW(), NOW(), NULL),
            (4, "Marsa Al Khor Business Park",  NOW(), NOW(), NULL),
            (4, "Mirdiff",  NOW(), NOW(), NULL),
            (4, "Muhaisanah",  NOW(), NOW(), NULL),
            (4, "Musallah Al Eid",  NOW(), NOW(), NULL),
            (4, "Mushrif Heights",  NOW(), NOW(), NULL),
            (4, "Mushrif Park",  NOW(), NOW(), NULL),
            (4, "Nadd Al Hamar",  NOW(), NOW(), NULL),
            (4, "Nad Al Sheba",  NOW(), NOW(), NULL),
            (4, "Nadd Shamma",  NOW(), NOW(), NULL),
            (4, "Naif",  NOW(), NOW(), NULL),
            (4, "Oud Al Muteena",  NOW(), NOW(), NULL),
            (4, "Port Saeed",  NOW(), NOW(), NULL),
            (4, "Ras Al Khor",  NOW(), NOW(), NULL),
            (4, "Sheikh Zayed Road",  NOW(), NOW(), NULL),
            (4, "Barsha Heights",  NOW(), NOW(), NULL),
            (4, "Dubai Textile City",  NOW(), NOW(), NULL),
            (4, "The Gardens",  NOW(), NOW(), NULL),
            (4, "The Greens",  NOW(), NOW(), NULL),
            (4, "Lagoons",  NOW(), NOW(), NULL),
            (4, "Meadows",  NOW(), NOW(), NULL),
            (4, "Old Town",  NOW(), NOW(), NULL),
            (4, "Palm Deira",  NOW(), NOW(), NULL),
            (4, "Nakhlat Jebel Ali",  NOW(), NOW(), NULL),
            (4, "The Palm Jumeirah",  NOW(), NOW(), NULL),
            (4, "Springs",  NOW(), NOW(), NULL),
            (4, "The Views",  NOW(), NOW(), NULL),
            (4, "The Villa",  NOW(), NOW(), NULL),
            (4, "World",  NOW(), NOW(), NULL),
            (4, "Tijara Town",  NOW(), NOW(), NULL),
            (4, "Umm Hurair 1",  NOW(), NOW(), NULL),
            (4, "Umm Hurair 2",  NOW(), NOW(), NULL),
            (4, "Umm Ramool",  NOW(), NOW(), NULL),
            (4, "Umm Al Sheif",  NOW(), NOW(), NULL),
            (4, "Umm Suqeim",  NOW(), NOW(), NULL),
            (4, "Uptown Motor City",  NOW(), NOW(), NULL),
            (4, "Wadi Al Amradi",  NOW(), NOW(), NULL),
            (4, "Warsan Village",  NOW(), NOW(), NULL),
            (4, "Zabeel",  NOW(), NOW(), NULL),
            (4, "Other",  NOW(), NOW(), NULL),
            (4, "Greens community",  NOW(), NOW(), NULL),
            (4, "Arabian Ranches ",  NOW(), NOW(), NULL),
            (4, "Downtown Burj Dubai",  NOW(), NOW(), NULL),
            (4, "Dubai Autodrome & Business Park",  NOW(), NOW(), NULL),
            (4, "Dubai Healthcare City",  NOW(), NOW(), NULL),
            (4, "Dubai Internet City",  NOW(), NOW(), NULL),
            (4, "Dubai Media City",  NOW(), NOW(), NULL),
            (4, "Global Village",  NOW(), NOW(), NULL),
            (4, "Golf Gardens",  NOW(), NOW(), NULL),
            (4, "Green Community",  NOW(), NOW(), NULL),
            (4, "Jebel Ali Free Zone Authority",  NOW(), NOW(), NULL),
            (4, "Jumeirah Village Circle",  NOW(), NOW(), NULL),
            (4, "Knowledge Village",  NOW(), NOW(), NULL),
            (4, "Mina Al Arab",  NOW(), NOW(), NULL),
            (4, "Sonapur",  NOW(), NOW(), NULL),
            (4, "The World Islands",  NOW(), NOW(), NULL),
            (4, "Dubai Outsource Zone",  NOW(), NOW(), NULL),
            (4, "Ducamz",  NOW(), NOW(), NULL),
            (4, "Bank Street Burdubai",  NOW(), NOW(), NULL),
            (4, "Khalid Bin Waleed",  NOW(), NOW(), NULL),
            (4, "Textile Market",  NOW(), NOW(), NULL),
            (4, "Meena Bazar",  NOW(), NOW(), NULL),
            (4, "Creek Road",  NOW(), NOW(), NULL),
            (4, "Old & New Consulate Areas",  NOW(), NOW(), NULL),
            (4, "Al Ghubaiba",  NOW(), NOW(), NULL),
            (4, "Port Rashid",  NOW(), NOW(), NULL),
            (4, "Dubai Immigration",  NOW(), NOW(), NULL),
            (4, "Rolla Street",  NOW(), NOW(), NULL),
            (4, "Golden Sands",  NOW(), NOW(), NULL),
            (4, "Sheikh Hamdan Colony",  NOW(), NOW(), NULL),
            (4, "Zabeel Park",  NOW(), NOW(), NULL),
            (4, "Karama Center",  NOW(), NOW(), NULL),
            (4, "Karama Post Office",  NOW(), NOW(), NULL),
            (4, "Oud Metha",  NOW(), NOW(), NULL),
            (4, "Rashid Hospital",  NOW(), NOW(), NULL),
            (4, "Dubai Courts",  NOW(), NOW(), NULL),
            (4, "Wafi City",  NOW(), NOW(), NULL),
            (4, "Lamcy Plaza",  NOW(), NOW(), NULL),
            (4, "Latifa Hospital",  NOW(), NOW(), NULL),
            (4, "Al-Wasl Road",  NOW(), NOW(), NULL),
            (4, "Jumeirah Beach Road",  NOW(), NOW(), NULL),
            (4, "Mazaya Center",  NOW(), NOW(), NULL),
            (4, "Police Colony",  NOW(), NOW(), NULL),
            (4, "Dubai Petroleum",  NOW(), NOW(), NULL),
            (4, "Al Safa 1",  NOW(), NOW(), NULL),
            (4, "Al Safa 2",  NOW(), NOW(), NULL),
            (4, "Safa Park",  NOW(), NOW(), NULL),
            (4, "Burj Al-Arab",  NOW(), NOW(), NULL),
            (4, "Jumeirah Beach Hotel",  NOW(), NOW(), NULL),
            (4, "Emaar Square",  NOW(), NOW(), NULL),
            (4, "Dubai Mall",  NOW(), NOW(), NULL),
            (4, "Humanitarian City",  NOW(), NOW(), NULL),
            (4, "Emirates towers",  NOW(), NOW(), NULL),
            (4, "Dubai World Trade Center",  NOW(), NOW(), NULL),
            (4, "Al Qouz Industrial Area",  NOW(), NOW(), NULL),
            (4, "Khaleej Times",  NOW(), NOW(), NULL),
            (4, "Al Khail Gate",  NOW(), NOW(), NULL),
            (4, "New Grand City Mall",  NOW(), NOW(), NULL),
            (4, "Al Marabea Street",  NOW(), NOW(), NULL),
            (4, "Oasis Center",  NOW(), NOW(), NULL),
            (4, "Time Square",  NOW(), NOW(), NULL),
            (4, "Al Qouz Mall",  NOW(), NOW(), NULL),
            (4, "Sidar Hospital",  NOW(), NOW(), NULL),
            (4, "Jebel Ali Police Station",  NOW(), NOW(), NULL),
            (4, "Jebel Ali Shooting Club",  NOW(), NOW(), NULL),
            (4, "Techno Park",  NOW(), NOW(), NULL),
            (4, "Logistic City",  NOW(), NOW(), NULL),
            (4, "Ducab",  NOW(), NOW(), NULL),
            (4, "Dugas",  NOW(), NOW(), NULL),
            (4, "Studio City",  NOW(), NOW(), NULL),
            (4, "Remraam",  NOW(), NOW(), NULL),
            (4, "Layan Community",  NOW(), NOW(), NULL),
            (4, "International Cricket Stadium",  NOW(), NOW(), NULL),
            (4, "Police Academy",  NOW(), NOW(), NULL),
            (4, "Souq Madinat Al-Jumeirah",  NOW(), NOW(), NULL),
            (4, "Dubal",  NOW(), NOW(), NULL),
            (4, "Jebel Ali DEWA",  NOW(), NOW(), NULL),
            (4, "Dubai College",  NOW(), NOW(), NULL),
            (4, "Barsha South",  NOW(), NOW(), NULL),
            (4, "The lakes",  NOW(), NOW(), NULL),
            (4, "DMCC",  NOW(), NOW(), NULL),
            (4, "Emaar Business Park",  NOW(), NOW(), NULL),
            (4, "Emirates Golf Club",  NOW(), NOW(), NULL),
            (4, "The Club House",  NOW(), NOW(), NULL),
            (4, "Jebel Ali Race Course",  NOW(), NOW(), NULL),
            (4, "Coral Botique Villas",  NOW(), NOW(), NULL),
            (4, "Dubai American Academy",  NOW(), NOW(), NULL),
            (4, "Baniyas Road",  NOW(), NOW(), NULL),
            (4, "Maktoum Road",  NOW(), NOW(), NULL),
            (4, "Salahuddin Road",  NOW(), NOW(), NULL),
            (4, "Nakheel ",  NOW(), NOW(), NULL),
            (4, "Naser Square",  NOW(), NOW(), NULL),
            (4, "Ayal Nasir",  NOW(), NOW(), NULL),
            (4, "Murshid Bazar",  NOW(), NOW(), NULL),
            (4, "Fish Market",  NOW(), NOW(), NULL),
            (4, "Hayat Regency",  NOW(), NOW(), NULL),
            (4, "Al Sabkha",  NOW(), NOW(), NULL),
            (4, "Al Ras",  NOW(), NOW(), NULL),
            (4, "Deira Abra",  NOW(), NOW(), NULL),
            (4, "Business Village Area",  NOW(), NOW(), NULL),
            (4, "Deira City Center",  NOW(), NOW(), NULL),
            (4, "Dnata",  NOW(), NOW(), NULL),
            (4, "Al Mamzar",  NOW(), NOW(), NULL),
            (4, "Al Hamriya Port",  NOW(), NOW(), NULL),
            (4, "Dubai Hospital",  NOW(), NOW(), NULL),
            (4, "Al Wuheida",  NOW(), NOW(), NULL),
            (4, "Qusais Industrial Area",  NOW(), NOW(), NULL),
            (4, "Lulu Village",  NOW(), NOW(), NULL),
            (4, "Dubai Taxi HQ",  NOW(), NOW(), NULL),
            (4, "Etisalat Academy",  NOW(), NOW(), NULL),
            (4, "Zulekha Hospital",  NOW(), NOW(), NULL),
            (4, "Al Mulla Plaza",  NOW(), NOW(), NULL),
            (4, "Dubai Police HQ",  NOW(), NOW(), NULL),
            (4, "Damascus Street",  NOW(), NOW(), NULL),
            (4, "Baghdad Street",  NOW(), NOW(), NULL),
            (4, "Dubai Golf Club",  NOW(), NOW(), NULL),
            (4, "Garhoud Residence Area",  NOW(), NOW(), NULL),
            (4, "Dubai International Airport",  NOW(), NOW(), NULL),
            (4, "Cargo Village",  NOW(), NOW(), NULL),
            (4, "Dubai Flower Center",  NOW(), NOW(), NULL),
            (4, "Dubai Airport Free Zone",  NOW(), NOW(), NULL),
            (4, "Samari Village",  NOW(), NOW(), NULL),
            (4, "Al Gandhi Complex",  NOW(), NOW(), NULL),
            (4, "Vegetable Market",  NOW(), NOW(), NULL),
            (4, "Al-Warsan",  NOW(), NOW(), NULL),
            (4, "Al-Aweer RTA Depo",  NOW(), NOW(), NULL),
            (4, "Al-Aweer Residential Area",  NOW(), NOW(), NULL),
            (4, "Dubai Outlet Mall",  NOW(), NOW(), NULL),
            (4, "Mizhar",  NOW(), NOW(), NULL),
            (4, "Al Maha",  NOW(), NOW(), NULL),
            (4, "Skycourts",  NOW(), NOW(), NULL),
            (4, "Uptown Mirdif",  NOW(), NOW(), NULL),
            (4, "DLC",  NOW(), NOW(), NULL),
            (4, "Ghoroob Community",  NOW(), NOW(), NULL),
            (4, "Shorooq Community",  NOW(), NOW(), NULL),
            (4, "Al Awir 1",  NOW(), NOW(), NULL),
            (4, "Al Awir 2",  NOW(), NOW(), NULL),
            (4, "Al Daghaya",  NOW(), NOW(), NULL),
            (4, "Al Eyas",  NOW(), NOW(), NULL),
            (4, "Al Fagaa",  NOW(), NOW(), NULL),
            (4, "Al Hathmah",  NOW(), NOW(), NULL),
            (4, "Al Hebiah 2",  NOW(), NOW(), NULL),
            (4, "Al Hebiah 3",  NOW(), NOW(), NULL),
            (4, "Al Kheeran First",  NOW(), NOW(), NULL),
            (4, "Al Layan 1",  NOW(), NOW(), NULL),
            (4, "Al Layan 2",  NOW(), NOW(), NULL),
            (4, "Al Lesaily",  NOW(), NOW(), NULL),
            (4, "Al Marmoom",  NOW(), NOW(), NULL),
            (4, "Al Merkadh",  NOW(), NOW(), NULL),
            (4, "Al Rowaiyah 3",  NOW(), NOW(), NULL),
            (4, "Al Selal",  NOW(), NOW(), NULL),
            (4, "Al Shindagha",  NOW(), NOW(), NULL),
            (4, "Al Thanyah 2",  NOW(), NOW(), NULL),
            (4, "Al Thanyah 3",  NOW(), NOW(), NULL),
            (4, "Al Thanyah 4",  NOW(), NOW(), NULL),
            (4, "Al Thanyah 5",  NOW(), NOW(), NULL),
            (4, "Al Ttay",  NOW(), NOW(), NULL),
            (4, "Al Wasl",  NOW(), NOW(), NULL),
            (4, "Al Yalayis 1",  NOW(), NOW(), NULL),
            (4, "Al Yalayis 2",  NOW(), NOW(), NULL),
            (4, "Al Yalayis 3",  NOW(), NOW(), NULL),
            (4, "Al Yalayis 4",  NOW(), NOW(), NULL),
            (4, "Al Yalayis 5",  NOW(), NOW(), NULL),
            (4, "Al Yufrah 1",  NOW(), NOW(), NULL),
            (4, "Al Yufrah 2",  NOW(), NOW(), NULL),
            (4, "Downtown",  NOW(), NOW(), NULL),
            (4, "Al Ghadeer Village",  NOW(), NOW(), NULL),
            (4, "Grayteesah",  NOW(), NOW(), NULL),
            (4, "Hadaeq Sheikh Mohammed Bin Rashid",  NOW(), NOW(), NULL),
            (4, "Hessyan 1",  NOW(), NOW(), NULL),
            (4, "Hessyan 2",  NOW(), NOW(), NULL),
            (4, "Jebel Ali 1",  NOW(), NOW(), NULL),
            (4, "Jebel Ali 2",  NOW(), NOW(), NULL),
            (4, "Jebel Ali 3",  NOW(), NOW(), NULL),
            (4, "Madinat Al Mataar",  NOW(), NOW(), NULL),
            (4, "Margab",  NOW(), NOW(), NULL),
            (4, "Margham",  NOW(), NOW(), NULL),
            (4, "Me\'aisem 1",  NOW(), NOW(), NULL),
            (4, "Me\'aisem 2",  NOW(), NOW(), NULL),
            (4, "Mena Jebel Ali",  NOW(), NOW(), NULL),
            (4, "Motor City",  NOW(), NOW(), NULL),
            (4, "Mugatrah",  NOW(), NOW(), NULL),
            (4, "Mushrif",  NOW(), NOW(), NULL),
            (4, "Nakhlat Deira",  NOW(), NOW(), NULL),
            (4, "Remah",  NOW(), NOW(), NULL),
            (4, "Rigga Al Buteen",  NOW(), NOW(), NULL),
            (4, "Saih Al Salam",  NOW(), NOW(), NULL),
            (4, "Saih Shuaib 1",  NOW(), NOW(), NULL),
            (4, "Saih Shuaib 2",  NOW(), NOW(), NULL),
            (4, "Saih Shuaib 3",  NOW(), NOW(), NULL),
            (4, "Saih Shuaib 4",  NOW(), NOW(), NULL),
            (4, "Trade Center 1",  NOW(), NOW(), NULL),
            (4, "Trade Center 2",  NOW(), NOW(), NULL),
            (4, "Umm Al Daman",  NOW(), NOW(), NULL),
            (4, "Umm Al Mo\'meneen",  NOW(), NOW(), NULL),
            (4, "Umm Eselay",  NOW(), NOW(), NULL),
            (4, "Umm Nahad 1",  NOW(), NOW(), NULL),
            (4, "Umm Nahad 2",  NOW(), NOW(), NULL),
            (4, "Umm Nahad 3",  NOW(), NOW(), NULL),
            (4, "Umm Nahad 4",  NOW(), NOW(), NULL),
            (4, "Wadi Al Safa 2",  NOW(), NOW(), NULL),
            (4, "Wadi Al Safa 3",  NOW(), NOW(), NULL),
            (4, "Wadi Al Safa 4",  NOW(), NOW(), NULL),
            (4, "Wadi Al Safa 5",  NOW(), NOW(), NULL),
            (4, "Wadi Al Safa 6",  NOW(), NOW(), NULL),
            (4, "Wadi Al Safa 7",  NOW(), NOW(), NULL),
            (4, "Wadi Alshabak",  NOW(), NOW(), NULL),
            (4, "Warsan 2",  NOW(), NOW(), NULL),
            (4, "Warsan 3",  NOW(), NOW(), NULL),
            (4, "Warsan 4",  NOW(), NOW(), NULL),
            (4, "Za\'abeel 1",  NOW(), NOW(), NULL),
            (4, "Za\'abeel 2",  NOW(), NOW(), NULL),
            (4, "Akoya by Damac",  NOW(), NOW(), NULL),
            (4, "Al Jiwin",  NOW(), NOW(), NULL),
            (4, "Al Khail Heights",  NOW(), NOW(), NULL),
            (4, "Al Reem",  NOW(), NOW(), NULL),
            (4, "Arjan",  NOW(), NOW(), NULL),
            (4, "Dubai Lifestyle City",  NOW(), NOW(), NULL),
            (4, "Falcon City of Wonders",  NOW(), NOW(), NULL),
            (4, "Legends Dubailand",  NOW(), NOW(), NULL),
            (4, "Majan",  NOW(), NOW(), NULL),
            (4, "Meydan Grand Views",  NOW(), NOW(), NULL),
            (4, "Millenium Estate by Meydan",  NOW(), NOW(), NULL),
            (4, "Saheel",  NOW(), NOW(), NULL),
            (4, "Samara",  NOW(), NOW(), NULL),
            (4, "Al Barari Residences",  NOW(), NOW(), NULL),
            (4, "The Palisades",  NOW(), NOW(), NULL),
            (4, "The Springs 1",  NOW(), NOW(), NULL),
            (4, "The Springs 10",  NOW(), NOW(), NULL),
            (4, "The Springs 11",  NOW(), NOW(), NULL),
            (4, "The Springs 12",  NOW(), NOW(), NULL),
            (4, "The Springs 14",  NOW(), NOW(), NULL),
            (4, "The Springs 15",  NOW(), NOW(), NULL),
            (4, "The Springs 2",  NOW(), NOW(), NULL),
            (4, "The Springs 3",  NOW(), NOW(), NULL),
            (4, "The Springs 4",  NOW(), NOW(), NULL),
            (4, "The Springs 5",  NOW(), NOW(), NULL),
            (4, "The Springs 6",  NOW(), NOW(), NULL),
            (4, "The Springs 7",  NOW(), NOW(), NULL),
            (4, "The Springs 8",  NOW(), NOW(), NULL),
            (4, "The Springs 9",  NOW(), NOW(), NULL),
            (4, "Zahra Townhouses and apartments",  NOW(), NOW(), NULL),
            (4, "Zen Garden",  NOW(), NOW(), NULL),
            (4, "Arabian Ranches 2",  NOW(), NOW(), NULL),
            (5, "Al Faseel Area", NOW(), NOW(), NOW()),
            (5, "Al Jaber Tower", NOW(), NOW(), NOW()),
            (5, "Al Wurayah Valley", NOW(), NOW(), NOW()),
            (5, "Fujairah Tower", NOW(), NOW(), NOW()),
            (5, "Fujairah Trade Centre", NOW(), NOW(), NOW()),
            (5, "Gurfah Area", NOW(), NOW(), NOW()),
            (5, "Merashid", NOW(), NOW(), NOW()),
            (5, "Mina Al Fajer", NOW(), NOW(), NOW()),
            (5, "Rul Dadna", NOW(), NOW(), NOW()),
            (5, "Sakamkam", NOW(), NOW(), NOW()),
            (5, "Khorfakkan", NOW(), NOW(), NOW()),
            (5, "Masafi", NOW(), NOW(), NOW()),
            (5, "Al Gail Shabiya", NOW(), NOW(), NOW()),
            (5, "Manama", NOW(), NOW(), NOW()),
            (5, "Taweelah", NOW(), NOW(), NOW()),
            (5, "Tawban", NOW(), NOW(), NOW()),
            (5, "Dhaid", NOW(), NOW(), NOW()),
            (5, "Dibba", NOW(), NOW(), NOW()),
            (5, "Fujairah Heritage", NOW(), NOW(), NOW()),
            (5, "Fujairah Football Club", NOW(), NOW(), NOW()),
            (5, "Fujairah Etisalat", NOW(), NOW(), NOW()),
            (5, "Fujairah Municipality", NOW(), NOW(), NOW()),
            (5, "Al-Gurfaaa", NOW(), NOW(), NOW()),
            (5, "Town Center", NOW(), NOW(), NOW()),
            (5, "Al-Ittihad", NOW(), NOW(), NOW()),
            (5, "Skamkam", NOW(), NOW(), NOW()),
            (5, "Madhab", NOW(), NOW(), NOW()),
            (5, "Al Badiya", NOW(), NOW(), NOW()),
            (5, "Friday Market", NOW(), NOW(), NOW()),
            (5, "Fujairah Port", NOW(), NOW(), NOW()),
            (5, "Al Baladiya", NOW(), NOW(), NOW()),
            (5, "Al-Faseel", NOW(), NOW(), NOW()),
            (5, "Fujairah City Center", NOW(), NOW(), NOW()),
            (5, "Musalla Eid Road", NOW(), NOW(), NOW()),
            (5, "Mudaifi", NOW(), NOW(), NOW()),
            (5, "Zubara", NOW(), NOW(), NOW()),
            (5, "Al Hayl Industrial Area", NOW(), NOW(), NOW()),
            (5, "Kalba", NOW(), NOW(), NOW()),
            (5, "Kalba Alwahda Str", NOW(), NOW(), NOW()),
            (5, "Kalba Corniche", NOW(), NOW(), NOW()),
            (5, "Khor Kalba", NOW(), NOW(), NOW()),
            (5, "Munae", NOW(), NOW(), NOW()),
            (5, "Tarif Str", NOW(), NOW(), NOW()),
            (5, "Fujairah Freezone 1 & 2", NOW(), NOW(), NOW()),
            (5, "Geearth", NOW(), NOW(), NOW()),
            (5, "Gurayya", NOW(), NOW(), NOW()),
            (5, "Murbah", NOW(), NOW(), NOW()),
            (5, "Qidfa", NOW(), NOW(), NOW()),
            (5, "Showka", NOW(), NOW(), NOW()),
            (5, "Siji", NOW(), NOW(), NOW()),
            (5, "Suhaila", NOW(), NOW(), NOW()),
            (5, "Wadi Saham", NOW(), NOW(), NOW()),
            (5, "Zubaida", NOW(), NOW(), NOW()),
            (6, "Al Qasmi Corniche Road", NOW(), NOW(), NOW()),
            (6, "Al-Khor Road", NOW(), NOW(), NOW()),
            (6, "Dafan Al Khor", NOW(), NOW(), NOW()),
            (6, "Jazirat Al Hamra", NOW(), NOW(), NOW()),
            (6, "Al Riffa", NOW(), NOW(), NOW()),
            (6, "Al Dhait South", NOW(), NOW(), NOW()),
            (6, "Al Dhait North", NOW(), NOW(), NOW()),
            (6, "Khuzam", NOW(), NOW(), NOW()),
            (6, "RAK Airport Area", NOW(), NOW(), NOW()),
            (6, "Kharran", NOW(), NOW(), NOW()),
            (6, "Nakheel", NOW(), NOW(), NOW()),
            (6, "Al Mamourah", NOW(), NOW(), NOW()),
            (6, "Qusaidat", NOW(), NOW(), NOW()),
            (6, "Al Brerat", NOW(), NOW(), NOW()),
            (6, "Julan", NOW(), NOW(), NOW()),
            (6, "Shamal", NOW(), NOW(), NOW()),
            (6, "Al Ghub", NOW(), NOW(), NOW()),
            (6, "Al Rams", NOW(), NOW(), NOW()),
            (6, "Al Mareed", NOW(), NOW(), NOW()),
            (6, "Mina Al Arab", NOW(), NOW(), NOW()),
            (6, "Adan", NOW(), NOW(), NOW()),
            (6, "Marjan Island", NOW(), NOW(), NOW()),
            (6, "Digdagga", NOW(), NOW(), NOW()),
            (6, "Jazirat Al Hamra-Free Zone 1", NOW(), NOW(), NOW()),
            (6, "Jazirat Al Hamra-Free Zone 2", NOW(), NOW(), NOW()),
            (6, "Khatt", NOW(), NOW(), NOW()),
            (6, "Khor Khwair", NOW(), NOW(), NOW()),
            (6, "Old Ras Al Khaimah", NOW(), NOW(), NOW()),
            (6, "Al Biyatah", NOW(), NOW(), NOW()),
            (7, "Abu Shaghara", NOW(), NOW(), NULL),
            (7, "Bu Tina", NOW(), NOW(), NULL),
            (7, "Al Abar", NOW(), NOW(), NULL),
            (7, "Al Azra", NOW(), NOW(), NULL),
            (7, "Al Darari", NOW(), NOW(), NULL),
            (7, "Al Falaj", NOW(), NOW(), NULL),
            (7, "Al Fayha", NOW(), NOW(), NULL),
            (7, "Al Fisht", NOW(), NOW(), NULL),
            (7, "Al Ghafia", NOW(), NOW(), NULL),
            (7, "Al Gharb", NOW(), NOW(), NULL),
            (7, "Ghubaiba", NOW(), NOW(), NULL),
            (7, "Al Ghuwair", NOW(), NOW(), NULL),
            (7, "Al Goaz", NOW(), NOW(), NULL),
            (7, "Al Hazzanah", NOW(), NOW(), NULL),
            (7, "Al Heera", NOW(), NOW(), NULL),
            (7, "Al Jazzat", NOW(), NOW(), NULL),
            (7, "Al Khaildia Suburb", NOW(), NOW(), NULL),
            (7, "Al Khan", NOW(), NOW(), NULL),
            (7, "Al Khezamia", NOW(), NOW(), NULL),
            (7, "Al Layyah Suburb", NOW(), NOW(), NULL),
            (7, "Al Majaz", NOW(), NOW(), NULL),
            (7, "Al Mamzar", NOW(), NOW(), NULL),
            (7, "Al Mirgab", NOW(), NOW(), NULL),
            (7, "Al Muntazah", NOW(), NOW(), NULL),
            (7, "Al Musallah", NOW(), NOW(), NULL),
            (7, "Al Nabba", NOW(), NOW(), NULL),
            (7, "Al Nahda", NOW(), NOW(), NULL),
            (7, "Al Nasserya", NOW(), NOW(), NULL),
            (7, "Al Nekhailat", NOW(), NOW(), NULL),
            (7, "Al Nud", NOW(), NOW(), NULL),
            (7, "Al Qadisiya", NOW(), NOW(), NULL),
            (7, "Al Qasimia", NOW(), NOW(), NULL),
            (7, "Al Quilaiaah", NOW(), NOW(), NULL),
            (7, "Al Ramaqiya", NOW(), NOW(), NULL),
            (7, "Al Ramla", NOW(), NOW(), NULL),
            (7, "Al Ramtha", NOW(), NOW(), NULL),
            (7, "Al Rifaah", NOW(), NOW(), NULL),
            (7, "Al Riqa Suburb", NOW(), NOW(), NULL),
            (7, "Al Seef", NOW(), NOW(), NULL),
            (7, "Al Shahab", NOW(), NOW(), NULL),
            (7, "Al Sharq", NOW(), NOW(), NULL),
            (7, "Al Soor", NOW(), NOW(), NULL),
            (7, "Al Subaikha", NOW(), NOW(), NULL),
            (7, "Al Sweihat", NOW(), NOW(), NULL),
            (7, "Al Talaa", NOW(), NOW(), NULL),
            (7, "Al Yarmook", NOW(), NOW(), NULL),
            (7, "Bu Danig", NOW(), NOW(), NULL),
            (7, "Dasman", NOW(), NOW(), NULL),
            (7, "Al Yash", NOW(), NOW(), NULL),
            (7, "Falah Camp", NOW(), NOW(), NULL),
            (7, "Halwan Suburb", NOW(), NOW(), NULL),
            (7, "Hydra Village", NOW(), NOW(), NULL),
            (7, "Industrial Area", NOW(), NOW(), NULL),
            (7, "Maysaloon", NOW(), NOW(), NULL),
            (7, "Mughaidir Suburb", NOW(), NOW(), NULL),
            (7, "Muwafjah", NOW(), NOW(), NULL),
            (7, "Muwailih Commercial", NOW(), NOW(), NULL),
            (7, "Queen Tower", NOW(), NOW(), NULL),
            (7, "Samnan", NOW(), NOW(), NULL),
            (7, "Sharqan", NOW(), NOW(), NULL),
            (7, "Sharjah Investment Center", NOW(), NOW(), NULL),
            (7, "Al Turffa", NOW(), NOW(), NULL),
            (7, "Um Tarrsfa", NOW(), NOW(), NULL),
            (7, "Wasit Suburb", NOW(), NOW(), NULL),
            (7, "Other", NOW(), NOW(), NULL),
            (7, "Bank Street", NOW(), NOW(), NULL),
            (7, "Al Mansoura", NOW(), NOW(), NULL),
            (7, "Margab", NOW(), NOW(), NULL),
            (7, "Jubail", NOW(), NOW(), NULL),
            (7, "Al Majarah", NOW(), NOW(), NULL),
            (7, "Qulaya", NOW(), NOW(), NULL),
            (7, "Al Manakh", NOW(), NOW(), NULL),
            (7, "Nahilak", NOW(), NOW(), NULL),
            (7, "Al Sabkha", NOW(), NOW(), NULL),
            (7, "Al-Faha", NOW(), NOW(), NULL),
            (7, "Al-Majaz 1,2,3", NOW(), NOW(), NULL),
            (7, "Al Taawun ", NOW(), NOW(), NULL),
            (7, "Khalidiya", NOW(), NOW(), NULL),
            (7, "Mualah", NOW(), NOW(), NULL),
            (7, "Naba", NOW(), NOW(), NULL),
            (7, "Naseriya", NOW(), NOW(), NULL),
            (7, "Al Riffa", NOW(), NOW(), NULL),
            (7, "Al Suweihan", NOW(), NOW(), NULL),
            (7, "Jamal Abdul Naser Street", NOW(), NOW(), NULL),
            (7, "Beach Road", NOW(), NOW(), NULL),
            (7, "Port Khalid", NOW(), NOW(), NULL),
            (7, "Buhairah Corniche", NOW(), NOW(), NULL),
            (7, "Sharjah Industrial Areas 1-14", NOW(), NOW(), NULL),
            (7, "Dubai Bypass Road", NOW(), NOW(), NULL),
            (7, "Al-Budai", NOW(), NOW(), NULL),
            (7, "Rahmanya", NOW(), NOW(), NULL),
            (7, "Saif Zone", NOW(), NOW(), NULL),
            (7, "Sharjah International Airport", NOW(), NOW(), NULL),
            (7, "Sharjah University", NOW(), NOW(), NULL),
            (7, "Al-Nahda Sharjah Areas", NOW(), NOW(), NULL),
            (7, "Sharjah Cricket Stadium", NOW(), NOW(), NULL),
            (7, "Industrial Area-13", NOW(), NOW(), NULL),
            (7, "Al Sajaa", NOW(), NOW(), NULL),
            (7, "Industrial Area-15", NOW(), NOW(), NULL),
            (7, "Industrial Area-17", NOW(), NOW(), NULL),
            (7, "Al Mahatah", NOW(), NOW(), NULL),
            (7, "Al Juraina 1", NOW(), NOW(), NULL),
            (7, "Al Juraina 2", NOW(), NOW(), NULL),
            (7, "Al Juraina 3", NOW(), NOW(), NULL),
            (7, "Al Juraina 4", NOW(), NOW(), NULL),
            (7, "Al Noof 1", NOW(), NOW(), NULL),
            (7, "Al Noof 2", NOW(), NOW(), NULL),
            (7, "Al Noof 3", NOW(), NOW(), NULL),
            (7, "Al Noof 4", NOW(), NOW(), NULL),
            (7, "Qarayen 1", NOW(), NOW(), NULL),
            (7, "Qarayen 2", NOW(), NOW(), NULL),
            (7, "Qarayen 3", NOW(), NOW(), NULL),
            (7, "Qarayen 4", NOW(), NOW(), NULL),
            (7, "Qarayen 5", NOW(), NOW(), NULL),
            (7, "Basateen Al Fallah", NOW(), NOW(), NULL),
            (7, "Al Atain", NOW(), NOW(), NULL),
            (7, "Barashi", NOW(), NOW(), NULL),
            (7, "Al bedea", NOW(), NOW(), NULL),
            (7, "Al Elm", NOW(), NOW(), NULL),
            (7, "Al Fallah Suburb", NOW(), NOW(), NULL),
            (7, "Al Suyoh 1", NOW(), NOW(), NULL),
            (7, "Al Suyoh 2", NOW(), NOW(), NULL),
            (7, "Al Suyoh 3", NOW(), NOW(), NULL),
            (7, "Al Suyoh 4", NOW(), NOW(), NULL),
            (7, "Al Suyoh 5", NOW(), NOW(), NULL),
            (7, "Al Suyoh 6", NOW(), NOW(), NULL),
            (7, "Al Suyoh 7", NOW(), NOW(), NULL),
            (7, "Al Suyoh 8", NOW(), NOW(), NULL),
            (7, "Al Tai", NOW(), NOW(), NULL),
            (7, "Qtah", NOW(), NOW(), NULL),
            (7, "Al Manazel", NOW(), NOW(), NULL),
            (7, "Al Zubair", NOW(), NOW(), NULL),
            (7, "Emirates Industrial City", NOW(), NOW(), NULL),
            (7, "Muzairah", NOW(), NOW(), NULL),
            (7, "Al Dafeen", NOW(), NOW(), NULL),
            (7, "Sharjah Airport FreeZone", NOW(), NOW(), NULL),
            (7, "Tasjeel Village", NOW(), NOW(), NULL),
            (7, "Souq Al Haraj", NOW(), NOW(), NULL),
            (7, "Sharjah Golf and Shooting club", NOW(), NOW(), NULL),
            (7, "Um Fannain", NOW(), NOW(), NULL),
            (7, "Al Qasba", NOW(), NOW(), NULL),
            (7, "Al Suyoh 9", NOW(), NOW(), NULL),
            (7, "Al Suyoh 10", NOW(), NOW(), NULL),
            (7, "Al Suyoh 11", NOW(), NOW(), NULL),
            (7, "Al Suyoh 12", NOW(), NOW(), NULL),
            (7, "Jawazia", NOW(), NOW(), NULL),
            (7, "Sehijan Suburb", NOW(), NOW(), NULL),
            (8, "Old Town Area", NOW(), NOW(), NOW()),
            (8, "Falaj Al Moalla", NOW(), NOW(), NOW()),
            (8, "Industrial Area", NOW(), NOW(), NOW()),
            (8, "Al Raafah", NOW(), NOW(), NOW()),
            (8, "Al Aqran", NOW(), NOW(), NOW()),
            (8, "Al Butain", NOW(), NOW(), NOW()),
            (8, "Al Rashdiya", NOW(), NOW(), NOW()),
            (8, "Al Surrah", NOW(), NOW(), NOW()),
            (8, "Lubsah", NOW(), NOW(), NOW()),
            (8, "Umm Al Thuaoob", NOW(), NOW(), NOW()),
            (8, "Kaber", NOW(), NOW(), NOW()),
            (8, "Al Haditha", NOW(), NOW(), NOW()),
            (8, "Al Hezam Al Akhdar", NOW(), NOW(), NOW()),
            (8, "Al Hazzan Area", NOW(), NOW(), NOW()),
            (8, "Al Hamra", NOW(), NOW(), NOW()),
            (8, "Al Hawiyah Area", NOW(), NOW(), NOW()),
            (8, "Al Dar Al Baida", NOW(), NOW(), NOW()),
            (8, "Al Raas 1", NOW(), NOW(), NOW()),
            (8, "Al Riqah", NOW(), NOW(), NOW()),
            (8, "Al Ramlah Area", NOW(), NOW(), NOW()),
            (8, "Al Rawdah", NOW(), NOW(), NOW()),
            (8, "Al Aahad Area", NOW(), NOW(), NOW()),
            (8, "Al Meidan", NOW(), NOW(), NOW()),
            (8, "Al Limghadar", NOW(), NOW(), NOW()),
            (8, "Laatein 2", NOW(), NOW(), NOW()),
            (8, "Mohadhub", NOW(), NOW(), NOW()),
            (8, "Bin Majid Flamingo Beach Resort", NOW(), NOW(), NOW()),
            (8, "Shabiyat Essa", NOW(), NOW(), NOW()),
            (8, "Mallah", NOW(), NOW(), NOW()),
            (8, "Al Maqtaa 1", NOW(), NOW(), NOW()),
            (8, "Al Maqtaa 2", NOW(), NOW(), NOW()),
            (8, "Al Maqtaa 3", NOW(), NOW(), NOW()),
            (8, "Laatein 1", NOW(), NOW(), NOW()),
            (8, "Al Neefah", NOW(), NOW(), NOW()),
            (8, "Al Zowair", NOW(), NOW(), NOW()),
            (8, "Khor Al Yeefrah", NOW(), NOW(), NOW()),
            (8, "Al Nekhailah", NOW(), NOW(), NOW()),
            (8, "Al Qarayen 1", NOW(), NOW(), NOW()),
            (8, "Al Boghah", NOW(), NOW(), NOW()),
            (8, "Al Qarayen 2", NOW(), NOW(), NOW()),
            (8, "Madinat Al Shuhada", NOW(), NOW(), NOW()),
            (8, "Al Hoboob 1", NOW(), NOW(), NOW()),
            (8, "Al Hoboob 2", NOW(), NOW(), NOW()),
            (8, "Oud Al Tayer 1", NOW(), NOW(), NOW()),
            (8, "Oud Al Tayer 2", NOW(), NOW(), NOW()),
            (8, "Al Shes", NOW(), NOW(), NOW()),
            (8, "Al Ghafat", NOW(), NOW(), NOW()),
            (8, "Al Suaihat 1", NOW(), NOW(), NOW()),
            (8, "Al Suaihat 2", NOW(), NOW(), NOW()),
            (8, "Mohammed Bin Rashid 1", NOW(), NOW(), NOW()),
            (8, "Mohammed Bin Rashid 2", NOW(), NOW(), NOW()),
            (8, "Khalifa City 1", NOW(), NOW(), NOW()),
            (8, "Khalifa City 2", NOW(), NOW(), NOW()),
            (8, "Umm Dera", NOW(), NOW(), NOW()),
            (8, "Shanteer", NOW(), NOW(), NOW()),
            (8, "Al Door 1", NOW(), NOW(), NOW()),
            (8, "Al Door 2", NOW(), NOW(), NOW()),
            (8, "Al Athaib", NOW(), NOW(), NOW()),
            (8, "Hezaiwah", NOW(), NOW(), NOW()),
            (8, "Meshara", NOW(), NOW(), NOW()),
            (8, "Khor Al Baida", NOW(), NOW(), NOW()),
            (8, "Oud Al Owaid", NOW(), NOW(), NOW()),
            (8, "Al Barqaa", NOW(), NOW(), NOW()),
            (8, "Tawi Rbaya", NOW(), NOW(), NOW()),
            (8, "Al Medfeq", NOW(), NOW(), NOW()),
            (8, "Al Shereiah", NOW(), NOW(), NOW()),
            (8, "Al Nabgghah", NOW(), NOW(), NOW()),
            (8, "Falaj Al Sheik", NOW(), NOW(), NOW()),
            (8, "Al Khour 1", NOW(), NOW(), NOW()),
            (8, "Al Khour 2", NOW(), NOW(), NOW()),
            (8, "Al Madr 1", NOW(), NOW(), NOW()),
            (8, "Al Madr 2", NOW(), NOW(), NOW()),
            (8, "Al Madr 3", NOW(), NOW(), NOW()),
            (8, "Al Abraq 1", NOW(), NOW(), NOW()),
            (8, "Al Abraq 2", NOW(), NOW(), NOW()),
            (8, "Al Salamh 1", NOW(), NOW(), NOW()),
            (8, "Al Salamh 2", NOW(), NOW(), NOW()),
            (8, "Al Salamh 3", NOW(), NOW(), NOW()),
            (8, "Dream Land", NOW(), NOW(), NOW()),
            (8, "Al Shebeakah", NOW(), NOW(), NOW())
        ');
    }
}
